### ISSUE TITLE
Stowrznie repo pod benchmarki

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/Benchmark_LLM#12]
## Jaki jest cel tego tego zadania

Z racji że benchmarki  strasznie się rozrosły i aby utrzymać porządek w  plikach potrzebujemy nowego repo gdzie będą przeprowadzane testy na LLM.

## Jak wygląda rozwiązanie?

Nowe repozytorium ale podpięte  pod  proejkt chatknml

## TODO:

- [x] Stworzenie Repo
- [x] Stworzenie label'ów 
- [x] Dołaczenie Użytkowników

**Comment by TheJimmyNowak** [comment]
LGTM
